import { chromium } from '/Users/samuelmaculuve/.npm/_npx/e41f203b7505f1fb/node_modules/playwright/index.mjs';
const BASE = 'http://localhost:4200', SHOTS = '/private/tmp/claude-501/-Users-samuelmaculuve-Downloads-gym/566ddb27-e7cb-4a89-9f05-6612681e018e/scratchpad/';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('response', async (r) => { const u = new URL(r.url()); if (u.pathname.startsWith('/api/') && r.request().method() !== 'GET') console.log('  ', r.request().method(), u.pathname, r.status(), (await r.text().catch(() => '')).slice(0, 160)); });
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
await page.goto(BASE + '/login');
await page.getByLabel('Email').fill('admin@gymflow.co.mz');
await page.getByLabel('Palavra-passe').fill('Admin@2026');
await page.getByRole('button', { name: 'Entrar' }).click();
await page.waitForURL(BASE + '/');
await page.waitForLoadState('networkidle');
await page.goto(BASE + '/members'); await page.waitForLoadState('networkidle');
await page.getByRole('button', { name: 'Novo membro' }).first().click();
await page.getByLabel('Nome completo').fill('Browser Teste Nhaca');
await page.getByLabel('Número de celular').fill('847778899');
await page.screenshot({ path: SHOTS + 'dbg-form.png' });
await page.getByRole('button', { name: /Cadastrar/ }).click();
await page.waitForTimeout(3000);
await page.screenshot({ path: SHOTS + 'dbg-after-create.png' });
await page.keyboard.press('Escape');
await page.goto(BASE + '/'); await page.waitForLoadState('networkidle');
await page.getByRole('button', { name: 'Menu do utilizador' }).click();
await page.screenshot({ path: SHOTS + 'dbg-menu.png' });
await page.getByRole('button', { name: 'Terminar sessão' }).click();
await page.waitForTimeout(3000);
console.log('URL após logout:', page.url());
await page.screenshot({ path: SHOTS + 'dbg-after-logout.png' });
await browser.close();
