process.env.NETLIFY_BLOBS_CONTEXT = Buffer.from(JSON.stringify({ edgeURL: 'http://127.0.0.1:45001', uncachedEdgeURL: 'http://127.0.0.1:45001', siteID: 'site', token: 'tok', deployID: 'd1' })).toString('base64');
const { getStore } = await import('@netlify/blobs');
const s = getStore({ name: 'probe', consistency: 'strong' });
const w = await s.set('k', new Blob(['hello']));
console.log('set:', JSON.stringify(w));
console.log('getMetadata:', JSON.stringify(await s.getMetadata('k')));
const g = await s.getWithMetadata('k', { type: 'blob' });
console.log('getWithMetadata etag:', JSON.stringify(g.etag));
const w2 = await s.set('k', new Blob(['x']), { onlyIfMatch: g.etag });
console.log('set onlyIfMatch(get etag):', JSON.stringify(w2));
const m = await s.getMetadata('k');
const w3 = await s.set('k', new Blob(['y']), { onlyIfMatch: m.etag });
console.log('set onlyIfMatch(meta etag):', JSON.stringify(w3), 'meta etag was', m.etag);
