/** Chaves das queries do TanStack Query, centralizadas para invalidação consistente. */
export const qk = {
  me: ['me'] as const,
  dashboard: ['dashboard'] as const,
  search: (q: string) => ['search', q] as const,
  members: ['members'] as const,
  memberList: (params: object) => ['members', 'list', params] as const,
  member: (id: string) => ['members', 'detail', id] as const,
  memberQr: (id: string) => ['members', 'qr', id] as const,
  plans: ['plans'] as const,
  subscriptions: ['subscriptions'] as const,
  subscriptionList: (params: object) => ['subscriptions', 'list', params] as const,
  payments: ['payments'] as const,
  paymentList: (params: object) => ['payments', 'list', params] as const,
  attendance: ['attendance'] as const,
  attendanceList: (params: object) => ['attendance', 'list', params] as const,
  notifications: ['notifications'] as const,
  notificationList: (params: object) => ['notifications', 'list', params] as const,
  templates: ['templates'] as const,
  reports: (kind: string, params: object) => ['reports', kind, params] as const,
  users: ['users'] as const,
  settings: ['settings'] as const,
  audit: (params: object) => ['audit', params] as const,
};
